[versions]
agp = "8.13.2"
protobuf = "4.36.2"
protobufPlugin = "0.10.0"
appcompat = "1.8.0"
recyclerview = "1.4.0"
drawerlayout = "1.2.0"
swiperefreshlayout = "1.2.0"
viewpager = "1.1.0"
legacySupportV13 = "1.0.0"
jmdns = "3.5.4"
junit = "4.13.2"
robolectric = "4.17"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
androidx-legacy-support-v13 = { module = "androidx.legacy:legacy-support-v13", version.ref = "legacySupportV13" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
