[versions]
agp = "8.13.2"
protobuf = "4.36.2"
protobufPlugin = "0.10.0"
supportLib = "28.0.0"
materialDialogs = "0.9.6.0"
jmdns = "3.5.4"
junit = "4.13.2"

[libraries]
support-v13 = { module = "com.android.support:support-v13", version.ref = "supportLib" }
support-appcompat = { module = "com.android.support:appcompat-v7", version.ref = "supportLib" }
support-recyclerview = { module = "com.android.support:recyclerview-v7", version.ref = "supportLib" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialogs" }
material-dialogs-commons = { module = "com.afollestad.material-dialogs:commons", version.ref = "materialDialogs" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
