package de.qspool.clementineremote.integration;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;


import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;

import de.qspool.clementineremote.App;
import de.qspool.clementineremote.backend.Clementine;
import de.qspool.clementineremote.backend.pb.ClementineMessageFactory;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.DownloadItem;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.Message;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.MsgType;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.Playlist;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.ReasonDisconnect;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.ResponseLibraryChunk;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.ResponseSongFileChunk;
import de.qspool.clementineremote.backend.pb.ClementineRemoteProtocolBuffer.SongMetadata;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assume.assumeTrue;

/**
 * Runs the app's protocol code against a real, headless Clementine (see clementine-it/).
 *
 * Skipped unless -Pclementine.host is given. The Clementine instance must hold the test
 * library generated by clementine-it/generate-music.sh, loaded as the active playlist.
 */
@RunWith(RobolectricTestRunner.class)
public class ClementineIntegrationTest {

    private static final int LIBRARY_SIZE = 10;

    @BeforeClass
    public static void requireClementine() {
        assumeTrue("clementine.host not set", ClementineSession.HOST != null);
    }

    @Before
    public void resetState() {
        App.Clementine = new Clementine();
        App.ClementineConnection = null;
    }

    @Test
    public void wrongAuthCodeIsRejected() {
        assumeTrue("Clementine has no auth code configured", ClementineSession.AUTH_CODE != 0);

        try (ClementineSession session =
                     ClementineSession.connect(ClementineSession.AUTH_CODE + 1, false)) {
            Message disconnect = session.await(MsgType.DISCONNECT);
            assertEquals(ReasonDisconnect.Wrong_Auth_Code,
                    disconnect.getResponseDisconnect().getReasonDisconnect());
        }
    }

    @Test
    public void connectReceivesInfoAndPlaylists() {
        try (ClementineSession session = ClementineSession.connect(ClementineSession.AUTH_CODE, false)) {
            Message info = session.await(MsgType.INFO);
            assertFalse(info.getResponseClementineInfo().getVersion().isEmpty());
            assertEquals(info.getResponseClementineInfo().getVersion(), App.Clementine.getVersion());

            Message playlists = session.await(MsgType.PLAYLISTS);
            int active = 0;
            for (Playlist p : playlists.getResponsePlaylists().getPlaylistList()) {
                if (p.getActive()) {
                    active++;
                    assertEquals(LIBRARY_SIZE, p.getItemCount());
                }
            }
            assertEquals(1, active);
            session.await(MsgType.FIRST_DATA_SENT_COMPLETE);
        }
    }

    @Test
    public void activePlaylistHoldsTheTestLibraryInOrder() {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            int playlistId = App.Clementine.getPlaylistManager().getActivePlaylistId();
            session.send(ClementineMessageFactory.buildRequestPlaylistSongs(playlistId));

            Message songs = session.await(MsgType.PLAYLIST_SONGS);
            List<SongMetadata> list = songs.getResponsePlaylistSongs().getSongsList();
            assertEquals(LIBRARY_SIZE, list.size());
            for (int i = 0; i < list.size(); i++) {
                assertEquals(String.format("Track %02d", i + 1), list.get(i).getTitle());
            }
            assertEquals("Test Artist A", list.get(0).getArtist());
            assertEquals("Album One", list.get(0).getAlbum());
        }
    }

    @Test
    public void playbackControls() {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            int playlistId = App.Clementine.getPlaylistManager().getActivePlaylistId();

            session.send(ClementineMessageFactory.buildRequestChangeSong(0, playlistId));
            session.await(MsgType.CURRENT_METAINFO, m -> title(m).equals("Track 01"));
            session.await(MsgType.PLAY);
            assertEquals(Clementine.State.PLAY, App.Clementine.getState());
            assertEquals("Track 01", App.Clementine.getCurrentSong().getTitle());

            session.send(MsgType.NEXT);
            session.await(MsgType.CURRENT_METAINFO, m -> title(m).equals("Track 02"));

            session.send(MsgType.PREVIOUS);
            session.await(MsgType.CURRENT_METAINFO, m -> title(m).equals("Track 01"));

            session.send(ClementineMessageFactory.buildTrackPosition(10));
            session.await(MsgType.UPDATE_TRACK_POSITION,
                    m -> m.getResponseUpdateTrackPosition().getPosition() >= 10);

            session.send(MsgType.PAUSE);
            session.await(MsgType.PAUSE);
            assertEquals(Clementine.State.PAUSE, App.Clementine.getState());

            session.send(MsgType.STOP);
            session.await(MsgType.STOP);
            assertEquals(Clementine.State.STOP, App.Clementine.getState());
        }
    }

    @Test
    public void volume() {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            session.send(ClementineMessageFactory.buildVolumeMessage(37));
            session.await(MsgType.SET_VOLUME, m -> m.getRequestSetVolume().getVolume() == 37);
            assertEquals(37, App.Clementine.getVolume());

            session.send(ClementineMessageFactory.buildVolumeMessage(80));
            session.await(MsgType.SET_VOLUME, m -> m.getRequestSetVolume().getVolume() == 80);
        }
    }

    @Test
    public void shuffleAndRepeat() {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            App.Clementine.setShuffleMode(Clementine.ShuffleMode.ALBUMS);
            session.send(ClementineMessageFactory.buildShuffle());
            session.await(MsgType.SHUFFLE);
            assertEquals(Clementine.ShuffleMode.ALBUMS, App.Clementine.getShuffleMode());

            App.Clementine.setRepeatMode(Clementine.RepeatMode.PLAYLIST);
            session.send(ClementineMessageFactory.buildRepeat());
            session.await(MsgType.REPEAT);
            assertEquals(Clementine.RepeatMode.PLAYLIST, App.Clementine.getRepeatMode());

            App.Clementine.setShuffleMode(Clementine.ShuffleMode.OFF);
            session.send(ClementineMessageFactory.buildShuffle());
            session.await(MsgType.SHUFFLE);
            App.Clementine.setRepeatMode(Clementine.RepeatMode.OFF);
            session.send(ClementineMessageFactory.buildRepeat());
            session.await(MsgType.REPEAT);
            assertEquals(Clementine.ShuffleMode.OFF, App.Clementine.getShuffleMode());
            assertEquals(Clementine.RepeatMode.OFF, App.Clementine.getRepeatMode());
        }
    }

    @Test
    public void libraryDownload() throws Exception {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            session.send(MsgType.GET_LIBRARY);

            ByteArrayOutputStream data = new ByteArrayOutputStream();
            ResponseLibraryChunk chunk;
            // Loop on the byte count: Clementine's chunk_count can overshoot by one.
            do {
                chunk = session.await(MsgType.LIBRARY_CHUNK).getResponseLibraryChunk();
                chunk.getData().writeTo(data);
            } while (data.size() < chunk.getSize());

            assertEquals(chunk.getSize(), data.size());
            assertEquals(chunk.getFileHash().toStringUtf8(), sha1Hex(data.toByteArray()));

            File db = File.createTempFile("library", ".db");
            try (FileOutputStream out = new FileOutputStream(db)) {
                data.writeTo(out);
            }
            SQLiteDatabase library = SQLiteDatabase.openDatabase(db.getPath(), null,
                    SQLiteDatabase.OPEN_READONLY);
            try (Cursor songs = library.rawQuery("SELECT count(*) FROM songs", null);
                 Cursor artists = library.rawQuery("SELECT count(DISTINCT artist) FROM songs", null)) {
                songs.moveToFirst();
                artists.moveToFirst();
                assertEquals(LIBRARY_SIZE, songs.getInt(0));
                assertEquals(2, artists.getInt(0));
            } finally {
                library.close();
                db.delete();
            }
        }
    }

    @Test
    public void songDownload() throws Exception {
        try (ClementineSession control = ClementineSession.connectAndSync()) {
            int playlistId = App.Clementine.getPlaylistManager().getActivePlaylistId();
            control.send(ClementineMessageFactory.buildRequestChangeSong(2, playlistId));
            control.await(MsgType.CURRENT_METAINFO, m -> title(m).equals("Track 03"));
            control.send(MsgType.PAUSE);

            // Downloads use their own connection, as the app's downloader does.
            try (ClementineSession downloader =
                         ClementineSession.connect(ClementineSession.AUTH_CODE, true)) {
                downloader.send(ClementineMessageFactory
                        .buildDownloadSongsMessage(DownloadItem.CurrentItem));

                Message total = downloader.await(MsgType.DOWNLOAD_TOTAL_SIZE);
                assertEquals(1, total.getResponseDownloadTotalSize().getFileCount());

                ResponseSongFileChunk offer =
                        downloader.await(MsgType.SONG_FILE_CHUNK).getResponseSongFileChunk();
                assertEquals(0, offer.getChunkNumber());
                assertEquals("Track 03", offer.getSongMetadata().getTitle());

                downloader.send(ClementineMessageFactory.buildSongOfferResponse(true));

                ByteArrayOutputStream data = new ByteArrayOutputStream();
                ResponseSongFileChunk chunk;
                do {
                    chunk = downloader.await(MsgType.SONG_FILE_CHUNK).getResponseSongFileChunk();
                    chunk.getData().writeTo(data);
                } while (data.size() < chunk.getSize());

                byte[] bytes = data.toByteArray();
                assertEquals(offer.getSize(), bytes.length);
                assertEquals(chunk.getFileHash().toStringUtf8(), sha1Hex(bytes));
                assertEquals("OggS", new String(bytes, 0, 4, "US-ASCII"));

                downloader.await(MsgType.DOWNLOAD_QUEUE_EMPTY);
            }
        }
    }

    @Test
    public void globalSearchFindsLibrarySongs() {
        try (ClementineSession session = ClementineSession.connectAndSync()) {
            session.send(ClementineMessageFactory.buildGlobalSearch("Test Artist B"));

            List<SongMetadata> results = new ArrayList<>();
            Message result = session.await(MsgType.GLOBAL_SEARCH_RESULT);
            results.addAll(result.getResponseGlobalSearch().getSongMetadataList());

            assertFalse(results.isEmpty());
            for (SongMetadata song : results) {
                assertEquals("Test Artist B", song.getArtist());
            }
        }
    }


    private static String title(Message message) {
        return message.getResponseCurrentMetadata().getSongMetadata().getTitle();
    }

    private static String sha1Hex(byte[] data) throws Exception {
        StringBuilder hex = new StringBuilder();
        for (byte b : MessageDigest.getInstance("SHA-1").digest(data)) {
            hex.append(String.format("%02x", b));
        }
        return hex.toString();
    }
}
